site_name: AI-Assisted Development Knowledge Base
site_description: Comprehensive knowledge base for AI-assisted development workflows and CDF deployment templates
site_author: Your Organization
repo_name: blake-samaha/knowledge_base
repo_url: https://github.com/blake-samaha/knowledge_base
site_url: https://blake-samaha.github.io/knowledge_base
edit_uri: edit/main/docs/

docs_dir: docs

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.result
    - navigation.instant.suggest
    - navigation.instant.tracking
    - navigation.instant.worker
    - navigation.instant.worker.offline
    - navigation.instant.worker.warmup
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Navigation structure
nav:
  - Home: index.md
  - Quick Start:
      - For Project Managers: ai_knowledge/quickstart_context_engineering.md
      - For Developers: ai_knowledge/advanced_prompting.md
  - AI Knowledge:
      - Overview: ai_knowledge/index.md
      - Context Engineering: ai_knowledge/context_engineering.md
      - Advanced Prompting: ai_knowledge/advanced_prompting.md
      - Prompt Techniques: ai_knowledge/prompt_techniques_overview.md
      - AI Workflows: ai_knowledge/ai_workflows/index.md
      - ROI Analysis: ai_knowledge/includes/roi_taxonomy.md
  - CDF Docs-as-Code:
      - Overview & Vision: cdf_project/overview.md
      - Core Concepts:
          - Docs-as-Code Framework: cdf_project/concepts/docs_as_code.md
          - Templates Concept: cdf_project/concepts/templates.md
          - Playbooks Concept: cdf_project/concepts/playbooks.md
          - Workflow Lifecycle: cdf_project/concepts/workflow_lifecycle.md
      - Templates Reference:
          - Solution Design Principles: cdf_project/templates/00_Solution_Design_Principles.md
          - Conceptual Model: cdf_project/templates/01_CONCEPTUAL_MODEL_TEMPLATE.md
          - Object Specification: cdf_project/templates/XX_Object_Specification_Template.md
      - Playbooks Reference:
          - Project Level Update: cdf_project/ai_playbooks/01_PROJECT_LEVEL_UPDATE.md
          - Module Bootstrap: cdf_project/ai_playbooks/02_MODULE_BOOTSTRAP.md
          - Object Level Update: cdf_project/ai_playbooks/03_OBJECT_LEVEL_UPDATE.md
          - Sanity Check: cdf_project/ai_playbooks/04_SANITY_CHECK.md
          - Toolkit YAML Sync: cdf_project/ai_playbooks/05_TOOLKIT_YAML_SYNC.md
          - Environment Promotion: cdf_project/ai_playbooks/06_ENVIRONMENT_PROMOTION.md
          - CI/CD Pipeline: cdf_project/ai_playbooks/07_CI_CD_PIPELINE.md
          - Data Ingestion Operations: cdf_project/ai_playbooks/08_DATA_INGESTION_OPERATIONS.md
          - Data Quality Validation: cdf_project/ai_playbooks/09_DATA_QUALITY_VALIDATION.md
          - Observability and Alerting: cdf_project/ai_playbooks/10_OBSERVABILITY_AND_ALERTING.md
          - Deprecation and Cleanup: cdf_project/ai_playbooks/11_DEPRECATION_AND_CLEANUP.md
      - Advanced Topics:
          - CI/CD Integration: cdf_project/advanced/ci_cd.md
          - Data Quality & Observability: cdf_project/advanced/data_quality.md
  - Governance: GOVERNANCE.md
  - Contributing: contributing.md

# Plugins
plugins:
  - search
  # Comment out:
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     enable_git_follow: false
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      use_pygments: true
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: pymdownx.slugs.slugify
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2024 Your Organization



# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn
